version: '3.7'

services:
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
            target: base
        volumes:
            - ./api/src:/api/src
        container_name: ffxi_crafting_api
        expose:
            - '$API_PORT'
        ports:
            - '$API_PORT:$API_PORT'
        command: npm start
    ffxi_crafting_app:
        build:
            context: ./ffxi-crafting-app
            dockerfile: Dockerfile
            target: base
        container_name: ffxi_crafting_app
        expose:
            - '$APP_PORT'
        ports:
            - '$APP_PORT:$APP_PORT'
        volumes:
            - ./ffxi-crafting-app/src:/app/src
        stdin_open: true
        tty: true
        command: npm start
    db:
        image: mysql
        # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
        # (this is just an example, not intended to be a production configuration)
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
