export enum Routes {
    Auction = 'auction',
    Craft = 'craft',
}

export enum Craft {
    Alchemy = 'Alchemy',
    Bonecraft = 'Bonecraft',
    Clothcraft = 'Clothcraft',
    Cooking = 'Cooking',
    Goldsmithing = 'Goldsmithing',
    Leathercraft = 'Leathercraft',
    Smithing = 'Smithing',
    Woodworking = 'Woodworking',
}

export enum Crystal {
    Fire = 'Fire',
    Ice = 'Ice',
    Wind = 'Wind',
    Earth = 'Earth',
    Lightning = 'Lightning',
    Water = 'Water',
    Light = 'Light',
    Dark = 'Dark',
}

export enum PriceType {
    Stack = 'stack',
    Single = 'single',
}

export enum StackSize {
    One = 1,
    Twelve = 12,
    Ninetynine = 99,
}

export enum Category {
    HandToHand = 'Hand-to-Hand',
    Daggers = 'Daggers',
    Swords = 'Swords',
    GreatSwords = 'Great Swords',
    Axes = 'Axes',
    GreatAxes = 'Great Axes',
    Scythes = 'Scythes',
    Polearms = 'Polearms',
    Katana = 'Katana',
    GreatKatana = 'Great Katana',
    Clubs = 'Clubs',
    Staves = 'Staves',
    Ranged = 'Ranged',
    Instruments = 'Instruments',
    Ammunition = 'Ammunition',
    FishingGear = 'Fishing Gear',
    Grips = 'Grips',
    PetItems = 'Pet Items',
    Shields = 'Shields',
    Head = 'Head',
    Neck = 'Neck',
    Body = 'Body',
    Hands = 'Hands',
    Waist = 'Waist',
    Legs = 'Legs',
    Feet = 'Feet',
    Back = 'Back',
    Earrings = 'Earrings',
    Rings = 'Rings',
    WhiteMagic = 'White Magic',
    BlackMagic = 'Black Magic',
    Songs = 'Songs',
    Ninjutsu = 'Ninjutsu',
    Summoning = 'Summoning',
    Dice = 'Dice',
    Geomancy = 'Geomancy',
    Medicines = 'Medicines',
    Furnishings = 'Furnishings',
    Smithing = 'Smithing',
    Goldsmithing = 'Goldsmithing',
    Clothcraft = 'Clothcraft',
    Leathercraft = 'Leathercraft',
    Bonecraft = 'Bonecraft',
    Woodworking = 'Woodworking',
    Alchemy = 'Alchemy',
    MeatAndEggs = 'Meat & Eggs',
    Seafood = 'Seafood',
    Vegetables = 'Vegetables',
    Soups = 'Soups',
    BreadAndRice = 'Bread & Rice',
    Sweets = 'Sweets',
    Drinks = 'Drinks',
    Ingredients = 'Ingredients',
    Fishing = 'Fishing',
    Crystals = 'Crystals',
    Misc = 'Misc.',
    Misc2 = 'Misc. 2',
    Misc3 = 'Misc. 3',
    BeastMade = 'Beast-made',
    Cards = 'Cards',
    NinjaTools = 'Ninja Tools',
    CursedItems = 'Cursed Items',
    Automaton = 'Automaton',
}
