enum Category {
    HandToHand = 'Weapons.Hand-to-Hand',
    Daggers = 'Weapons.Daggers',
    Swords = 'Weapons.Swords',
    GreatSwords = 'Weapons.Great Swords',
    Axes = 'Weapons.Axes',
    GreatAxes = 'Weapons.Great Axes',
    Scythes = 'Weapons.Scythes',
    Polearms = 'Weapons.Polearms',
    Katana = 'Weapons.Katana',
    GreatKatana = 'Weapons.Great Katana',
    Clubs = 'Weapons.Clubs',
    Staves = 'Weapons.Staves',
    Ranged = 'Weapons.Ranged',
    Instruments = 'Weapons.Instruments',
    Ammunition = 'Weapons.Ammo & Misc.Ammunition',
    FishingGear = 'Weapons.Ammo & Misc.Fishing Gear',
    Grips = 'Weapons.Ammo & Misc.Grips',
    PetItems = 'Weapons.Ammo & Misc.Pet Items',
    Shields = 'Armor.Shields',
    Head = 'Armor.Head',
    Neck = 'Armor.Neck',
    Body = 'Armor.Body',
    Hands = 'Armor.Hands',
    Waist = 'Armor.Waist',
    Legs = 'Armor.Legs',
    Feet = 'Armor.Feet',
    Back = 'Armor.Back',
    Earrings = 'Armor.Earrings',
    Rings = 'Armor.Rings',
    WhiteMagic = 'Scrolls.White Magic',
    BlackMagic = 'Scrolls.Black Magic',
    Songs = 'Scrolls.Songs',
    Ninjutsu = 'Scrolls.Ninjutsu',
    Summoning = 'Scrolls.Summoning',
    Dice = 'Scrolls.Dice',
    Geomancy = 'Scrolls.Geomancy',
    Medicine = 'Medicines',
    Furnishings = 'Furnishings',
    Smithing = 'Materials.Smithing',
    Goldsmithing = 'Materials.Goldsmithing',
    Clothcraft = 'Materials.Clothcraft',
    Leathercraft = 'Materials.Leathercraft',
    Bonecraft = 'Materials.Bonecraft',
    Woodworking = 'Materials.Woodworking',
    Alchemy = 'Materials.Alchemy',
    MeatAndEggs = 'Food.Meals.Meat & Eggs',
    Seafood = 'Food.Meals.Seafood',
    Vegetables = 'Food.Meals.Vegetables',
    Soups = 'Food.Meals.Soups',
    BreadAndRice = 'Food.Meals.Bread & Rice',
    Sweets = 'Food.Meals.Sweets',
    Drinks = 'Food.Meals.Drinks',
    Ingredients = 'Food.Ingredients',
    Fishing = 'Food.Fishing',
    Crystals = 'Crystals',
    Misc = 'Others.Misc.',
    Misc2 = 'Others.Misc 2',
    Misc3 = 'Others.Misc 3',
    BeastMade = 'Others.Beast-made',
    Cards = 'Others.Cards',
    NinjaTools = 'Others.Ninja Tools',
    CursedItems = 'Others.Cursed Items',
    Automaton = 'Others.Automaton',
}

export const CATEGORY_OPTIONS = Object.entries(Category)
    .map(([key, value]) => {
        return {
            value,
            label: key,
        };
    })
    .sort((a, b) => (a.label > b.label ? 1 : -1));
