export const CRAFT = {
  ALCHEMY: "Alchemy",
  BONECRAFT: "Bonecraft",
  CLOTHCRAFT: "Clothcraft",
  COOKING: "Cooking",
  GOLDSMITHING: "Goldsmithing",
  LEATHERCRAFT: "Leathercraft",
  SMITHING: "Smithing",
  WOODWORKING: "Woodworking",
};

export const CRYSTAL = {
  FIRE: "Fire",
  ICE: "Ice",
  WIND: "Wind",
  EARTH: "Earth",
  LIGHTNING: "Lightning",
  WATER: "Water",
  LIGHT: "Light",
  DARK: "Dark",
};

export const PRICE_TYPE = {
  STACK: "stack",
  SINGLE: "single",
};

export const STACK_SIZE = {
  ONE: 1,
  TWELVE: 12,
  NINETYNINE: 99,
};

export const CATEGORY = {
  HandToHand: "Hand-to-Hand",
  Daggers: "Daggers",
  Swords: "Swords",
  GreatSwords: "Great Swords",
  Axes: "Axes",
  GreatAxes: "Great Axes",
  Scythes: "Scythes",
  Polearms: "Polearms",
  Katana: "Katana",
  GreatKatana: "Great Katana",
  Clubs: "Clubs",
  Staves: "Staves",
  Ranged: "Ranged",
  Instruments: "Instruments",
  Ammunition: "Ammunition",
  FishingGear: "Fishing Gear",
  Grips: "Grips",
  PetItems: "Pet Items",
  Shields: "Shields",
  Head: "Head",
  Neck: "Neck",
  Body: "Body",
  Hands: "Hands",
  Waist: "Waist",
  Legs: "Legs",
  Feet: "Feet",
  Back: "Back",
  Earrings: "Earrings",
  Rings: "Rings",
  WhiteMagic: "White Magic",
  BlackMagic: "Black Magic",
  Songs: "Songs",
  Ninjutsu: "Ninjutsu",
  Summoning: "Summoning",
  Dice: "Dice",
  Geomancy: "Geomancy",
  Medicines: "Medicines",
  Furnishings: "Furnishings",
  Smithing: "Smithing",
  Goldsmithing: "Goldsmithing",
  Clothcraft: "Clothcraft",
  Leathercraft: "Leathercraft",
  Bonecraft: "Bonecraft",
  Woodworking: "Woodworking",
  Alchemy: "Alchemy",
  MeatAndEggs: "Meat & Eggs",
  Seafood: "Seafood",
  Vegetables: "Vegetables",
  Soups: "Soups",
  BreadAndRice: "Bread & Rice",
  Sweets: "Sweets",
  Drinks: "Drinks",
  Ingredients: "Ingredients",
  Fishing: "Fishing",
  Crystals: "Crystals",
  Misc: "Misc.",
  Misc2: "Misc. 2",
  Misc3: "Misc. 3",
  BeastMade: "Beast-made",
  Cards: "Cards",
  NinjaTools: "Ninja Tools",
  CursedItems: "Cursed Items",
  Automaton: "Automaton",
};
